// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDY6ZtID_E2IZ5zb8LTOd-MuWR8uba5jZ0',
    appId: '1:792261349635:web:cf209f12fd29a3d9625936',
    messagingSenderId: '792261349635',
    projectId: 'section-32a6e',
    authDomain: 'section-32a6e.firebaseapp.com',
    storageBucket: 'section-32a6e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1ghI4MuiDkrHDbM4UYpQn0Q0YvA2mB6k',
    appId: '1:792261349635:android:683f478db4538649625936',
    messagingSenderId: '792261349635',
    projectId: 'section-32a6e',
    storageBucket: 'section-32a6e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsAGUVavTGhPY9FSngLLFPOA4Th8iZ2lU',
    appId: '1:792261349635:ios:bd52a3db215d0e76625936',
    messagingSenderId: '792261349635',
    projectId: 'section-32a6e',
    storageBucket: 'section-32a6e.firebasestorage.app',
    iosBundleId: 'com.example.section',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsAGUVavTGhPY9FSngLLFPOA4Th8iZ2lU',
    appId: '1:792261349635:ios:bd52a3db215d0e76625936',
    messagingSenderId: '792261349635',
    projectId: 'section-32a6e',
    storageBucket: 'section-32a6e.firebasestorage.app',
    iosBundleId: 'com.example.section',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDY6ZtID_E2IZ5zb8LTOd-MuWR8uba5jZ0',
    appId: '1:792261349635:web:7c8e9e1b3f186026625936',
    messagingSenderId: '792261349635',
    projectId: 'section-32a6e',
    authDomain: 'section-32a6e.firebaseapp.com',
    storageBucket: 'section-32a6e.firebasestorage.app',
  );
}
